[tool.briefcase]
project_name = "Inch to MM App"
bundle = "com.mklotz.inmmconv"
version = "0.0.1"
url = "https://github.com/1stS1d/mklotz"
license = "MIT license"
author = '1stS1d'
author_email = "jack7nugget@gmail.com"

[tool.briefcase.app.inmmconv]
formal_name = "Inch to MM App"
description = "For converting between inches and millimeters quickly."
icon = "src/inmmconv/resources/inmmconv"
sources = ['src/inmmconv']
requires = []


[tool.briefcase.app.inmmconv.macOS]
requires = [
    'toga-cocoa>=0.3.0.dev18',
]

[tool.briefcase.app.inmmconv.linux]
requires = [
    'toga-gtk>=0.3.0.dev18',
]
system_requires = [
    'libgirepository1.0-dev',
    'libcairo2-dev',
    'libpango1.0-dev',
    'libwebkitgtk-3.0-0',
    'gir1.2-webkit-3.0',
]

[tool.briefcase.app.inmmconv.windows]
requires = [
    'toga-winforms>=0.3.0.dev18',
]

# Mobile deployments
[tool.briefcase.app.inmmconv.iOS]
requires = [
    'toga-iOS>=0.3.0.dev18',
]

[tool.briefcase.app.inmmconv.android]
requires = [
    'toga-android>=0.3.0.dev18',
]
